DROP TABLE IF EXISTS archive_dates CASCADE;
DROP TABLE IF EXISTS patches CASCADE;
DROP TABLE IF EXISTS files CASCADE;
DROP TABLE IF EXISTS commits CASCADE;
DROP TABLE IF EXISTS issues CASCADE;
DROP TABLE IF EXISTS repositories CASCADE;
